# Generated by Django 3.2.9 on 2021-12-05 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_users_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'ユーザー'},
        ),
        migrations.AlterField(
            model_name='users',
            name='address1',
            field=models.CharField(max_length=100, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='users',
            name='address2',
            field=models.CharField(max_length=100, verbose_name='番地'),
        ),
        migrations.AlterField(
            model_name='users',
            name='address3',
            field=models.CharField(max_length=200, verbose_name='方書'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='有効'),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='管理者'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=100, verbose_name='苗字'),
        ),
        migrations.AlterField(
            model_name='users',
            name='zip_code',
            field=models.CharField(max_length=10, verbose_name='郵便番号'),
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('gender', models.PositiveIntegerField(verbose_name='性別')),
                ('birthday', models.DateField(verbose_name='誕生日')),
                ('picture', models.FileField(blank=True, upload_to='pet/', verbose_name='画像')),
                ('comment', models.CharField(max_length=1000)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ペット',
                'db_table': 'pets',
                'ordering': ('users',),
            },
        ),
    ]
