# Generated by Django 3.2.9 on 2021-12-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211205_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pets',
            options={'ordering': ('user',), 'verbose_name_plural': 'ペット'},
        ),
        migrations.RenameField(
            model_name='pets',
            old_name='users',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=100, verbose_name='飼い主様の苗字'),
        ),
    ]
