# Generated by Django 3.2.9 on 2021-12-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211205_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='birthmonth',
            field=models.PositiveIntegerField(null=True, verbose_name='誕生月'),
        ),
    ]
