# Generated by Django 3.2.9 on 2021-12-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_pets_birthmonth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='birthmonth',
            field=models.PositiveIntegerField(verbose_name='誕生月'),
        ),
    ]
