# Generated by Django 3.2.9 on 2021-12-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_pets_birthmonth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pets',
            name='birthmonth',
        ),
        migrations.AddField(
            model_name='pets',
            name='birthday_day',
            field=models.PositiveIntegerField(default=1, verbose_name='誕生日の日付'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pets',
            name='birthday_month',
            field=models.PositiveIntegerField(default=1, verbose_name='誕生日の月'),
            preserve_default=False,
        ),
    ]
