# Generated by Django 3.2.9 on 2021-12-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211209_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='comment',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='users',
            name='address1',
            field=models.CharField(blank=True, max_length=100, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='users',
            name='address2',
            field=models.CharField(blank=True, max_length=100, verbose_name='番地'),
        ),
        migrations.AlterField(
            model_name='users',
            name='address3',
            field=models.CharField(blank=True, max_length=200, verbose_name='方書'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='users',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='郵便番号'),
        ),
    ]
