# Generated by Django 3.2.9 on 2021-12-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20211209_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='picture',
            field=models.FileField(upload_to='pet/', verbose_name='画像'),
        ),
    ]
